apiVersion: apps/v1
kind: Deployment

metadata:
  name: architect-ai-frontend

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: architect-ai

  template:
    metadata:
      labels:
          app: architect-ai

    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
        