apiVersion: v1
kind: Service

metadata:
  name: architect-ai-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: architect-ai

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}